apiVersion: v1
kind: Service
metadata:
  name: airflow-db-executor-svc
spec:
  type: NodePort
  ports:
  - nodePort: 31726
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: airflow-db-executor