apiVersion: v1
kind: Service
metadata:
  name: airflow-executor
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    name: airflow-executor
status:
  loadBalancer: {}