apiVersion: v1
kind: Service
metadata:
  name: airflow-db-executor
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: airflow-db-executor
  sessionAffinity: None
status:
  loadBalancer: {}