apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-db-executor
  template:
    metadata:
      labels:
        name: airflow-db-executor
    spec:
      containers:
      - name: airflow-db-executor
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: airflow-db-config
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 5432
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
          mountPropagation: None
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: postgresql-data
