apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker-base
spec:
  restartPolicy: Never
  containers:
    # Each Airflow pod_template_file must have a container named "base" at the pod.spec.containers[0] position
    - name: base
      image: kubegut/airflowk8sdemo:latest
      imagePullPolicy: Always
      ports: []
      command: []
      envFrom:
      - configMapRef:
      # For airflow system use
          name: first-airflow-worker-config
      resources:
        limits:
          cpu: 200m
          memory: "512Mi"
        requests:
          cpu: 300m
          memory: "1024Mi"
      volumeMounts:
        - name: airflow-logs
          mountPath: /opt/airflow/logs/
          mountPropagation: None
  volumes:
    - emptyDir: {}
      name: airflow-data
    - emptyDir: {}
      name: airflow-logs
        